
name: Deploy EC2 with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy-ec2:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials Using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # Use the desired version of Terraform

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Configuration
        run: terraform plan
      - name: hello world setup
        run: echo "hello world"
